// this file auto-generated by the embedded processor assembler -- edits likely to be overwritten

#ifndef _KIWI_GEN_H_
#define _KIWI_GEN_H_

// from assembler DEF directives:

#define SDR_GPS_BUILD    // DEFh 0x1
#define VAL_SDR_GPS_BUILD 1
//#define GPS_ONLY_BUILD    // DEFh 0x0
#define VAL_GPS_ONLY_BUILD 0
#define FPGA_VER 1    // DEFp 0x1
#define FW_ID 20480    // DEFp 0x5000
#define ADC_BITS 14    // DEFp 0xe
#define DEFAULT_NSYNC 2    // DEFp 0x2
#define USE_CPU_MULT    // DEFh 0x1
#define VAL_USE_CPU_MULT 1
#define USE_MIX_DDS    // DEFh 0x1
#define VAL_USE_MIX_DDS 1
#define USE_GEN    // DEFh 0x1
#define VAL_USE_GEN 1
//#define USE_HBEAT    // DEFh 0x0
#define VAL_USE_HBEAT 0
#define USE_LOGGER    // DEFh 0x1
#define VAL_USE_LOGGER 1
#define USE_CPU_CTR    // DEFh 0x1
#define VAL_USE_CPU_CTR 1
#define USE_DEBUG    // DEFh 0x1
#define VAL_USE_DEBUG 1
#define USE_VIVADO    // DEFh 0x1
#define VAL_USE_VIVADO 1
#define ARTIX_7    // DEFh 0x1
#define VAL_ARTIX_7 1
//#define QUICK_BUILD    // DEFh 0x0
#define VAL_QUICK_BUILD 0
//#define SPI_PUMP_CHECK    // DEFh 0x0
#define VAL_SPI_PUMP_CHECK 0
//#define STACK_CHECK    // DEFh 0x0
#define VAL_STACK_CHECK 0
//#define SND_SEQ_CHECK    // DEFh 0x0
#define VAL_SND_SEQ_CHECK 0
//#define SND_TIMING_CK    // DEFh 0x0
#define VAL_SND_TIMING_CK 0
#define SPI_32    // DEFh 0x1
#define VAL_SPI_32 1
//#define MEAS_CIC_OUT    // DEFh 0x0
#define VAL_MEAS_CIC_OUT 0
#define NUM_CMDS 38    // DEFp 0x26
#define GPS_CHANS 12    // DEFp 0xc
#define RX_CHANS 4    // DEFp 0x4
#define WF_CHANS 4    // DEFp 0x4
#define FPGA_ID 3    // DEFp 0x3
//#define USE_RX_SEQ    // DEFh 0x0
#define VAL_USE_RX_SEQ 0
#define SND_12000    // DEFh 0x1
#define VAL_SND_12000 1
//#define SND_9600    // DEFh 0x0
#define VAL_SND_9600 0
#define SND_RATE 12000    // DEFp 0x2ee0
#define RX1_DECIM 505    // DEFp 0x1f9
#define RX2_DECIM 11    // DEFp 0xb
#define NRX_BUFS 8    // DEFp 0x8
#define NRX_SAMPS 84    // DEFp 0x54
#define NRX_SAMPS_RPT 8    // DEFp 0x8
#define NRX_SAMPS_LOOP 42    // DEFp 0x2a
//#define USE_RX_CIC24    // DEFh 0x0
#define VAL_USE_RX_CIC24 0
#define RX1_BITS 22    // DEFp 0x16
#define RX2_BITS 18    // DEFp 0x12
#define RXO_BITS 24    // DEFp 0x18
#define RX1_STAGES 3    // DEFp 0x3
#define RX2_STAGES 5    // DEFp 0x5
#define MAX_ZOOM 14    // DEFp 0xe
#define NWF_SAMPS 482    // DEFp 0x1e2
#define NWF_SAMPS_RPT 48    // DEFp 0x30
#define NWF_SAMPS_LOOP 10    // DEFp 0xa
#define NWF_SAMPS_REM 2    // DEFp 0x2
#define USE_WF_1CIC    // DEFh 0x1
#define VAL_USE_WF_1CIC 1
#define USE_WF_PRUNE    // DEFh 0x1
#define VAL_USE_WF_PRUNE 1
#define USE_WF_CIC24    // DEFh 0x1
#define VAL_USE_WF_CIC24 1
//#define USE_WF_MEM24    // DEFh 0x0
#define VAL_USE_WF_MEM24 0
//#define USE_WF_NEW    // DEFh 0x0
#define VAL_USE_WF_NEW 0
#define WF1_STAGES 5    // DEFp 0x5
#define WF2_STAGES 5    // DEFp 0x5
#define WF1_BITS 24    // DEFp 0x18
#define WF2_BITS 24    // DEFp 0x18
#define WFO_BITS 16    // DEFp 0x10
#define WF_1CIC_MAXD 8192    // DEFp 0x2000
#define WF_2CIC_MAXD 0    // DEFp 0x0
#define MAX_NAV_BITS 64    // DEFp 0x40
#define GPS_SAMPS 256    // DEFp 0x100
#define GPS_IQ_SAMPS 510    // DEFp 0x1fe
#define GPS_IQ_SAMPS_W 1020    // DEFp 0x3fc
#define NADC_SAMPS 512    // DEFp 0x200
#define GET_CHAN_IQ 1    // DEFb 0x1
#define GET_SRQ 2    // DEFb 0x2
#define GET_SNAPSHOT 4    // DEFb 0x4
#define HOST_RX 8    // DEFb 0x8
#define GET_RX_SRQ 16    // DEFb 0x10
#define GET_CPU_CTR0 32    // DEFb 0x20
#define GET_CPU_CTR1 64    // DEFb 0x40
#define GET_CPU_CTR2 128    // DEFb 0x80
#define GET_CPU_CTR3 256    // DEFb 0x100
#define GET_STATUS 512    // DEFb 0x200
#define HOST_TX 1    // DEFb 0x1
#define SET_MASK 2    // DEFb 0x2
#define SET_CHAN 4    // DEFb 0x4
#define SET_CA_NCO 8    // DEFb 0x8
#define SET_LO_NCO 16    // DEFb 0x10
#define SET_SV 32    // DEFb 0x20
#define SET_PAUSE 64    // DEFb 0x40
#define SET_CTRL 1    // DEFb 0x1
#define SET_RX_CHAN 2    // DEFb 0x2
#define SET_RX_FREQ 4    // DEFb 0x4
#define SET_RX_NSAMPS 8    // DEFb 0x8
#define SET_GEN 16    // DEFb 0x10
#define SET_GEN_ATTN 32    // DEFb 0x20
#define SET_WF_FREQ 64    // DEFb 0x40
#define SET_WF_DECIM 128    // DEFb 0x80
#define SET_WF_CHAN 256    // DEFb 0x100
#define WF_SAMPLER_RST 512    // DEFb 0x200
#define HOST_RST 1    // DEFb 0x1
#define HOST_RDY 2    // DEFb 0x2
#define GPS_SAMPLER_RST 4    // DEFb 0x4
#define GET_GPS_SAMPLES 8    // DEFb 0x8
#define GET_MEMORY 16    // DEFb 0x10
#define GET_LOG 32    // DEFb 0x20
#define PUT_LOG 64    // DEFb 0x40
#define LOG_RST 128    // DEFb 0x80
#define CPU_CTR_CLR 256    // DEFb 0x100
#define CPU_CTR_ENA 512    // DEFb 0x200
#define CPU_CTR_DIS 1024    // DEFb 0x400
#define GET_RX_SAMP 1    // DEFb 0x1
#define RX_BUFFER_RST 2    // DEFb 0x2
#define RX_GET_BUF_CTR 4    // DEFb 0x4
#define SET_WF_CONTIN 8    // DEFb 0x8
#define GET_WF_SAMP_I 16    // DEFb 0x10
#define GET_WF_SAMP_Q 32    // DEFb 0x20
#define CLR_RX_OVFL 64    // DEFb 0x40
#define FREEZE_TOS 128    // DEFb 0x80
#define WF_SAMP_RD_RST 1    // DEFb 0x1
#define WF_SAMP_WR_RST 2    // DEFb 0x2
#define WF_SAMP_CONTIN 4    // DEFb 0x4
#define WF_SAMP_SYNC 8    // DEFb 0x8
#define STAT_FPGA_ID 15    // DEFp 0xf
#define STAT_CLOCK_ID 240    // DEFp 0xf0
#define STAT_FPGA_VER 3840    // DEFp 0xf00
#define STAT_FW_ID 28672    // DEFp 0x7000
#define STAT_OVFL 32768    // DEFb 0x8000
#define CTRL_OSC_EN 256    // DEFb 0x100
#define CTRL_EEPROM_WP 512    // DEFb 0x200
#define CTRL_USE_GEN 1024    // DEFb 0x400
#define CTRL_TEST_MODE 2048    // DEFb 0x800
#define CTRL_INTERRUPT 4096    // DEFb 0x1000
#define HEARTBEAT_IND    // DEFh 0x200
#define VAL_HEARTBEAT_IND 512
#define CTRL_UNUSED_OUT 32768    // DEFb 0x8000

#endif
